fluent-bit:
  enabled: false
  config:
    batchSize: "1048576"

promtail:
  enabled: true
  tolerations:
    - effect: NoSchedule
      operator: Exists

loki:
  persistence:
    enabled: true
    size: 20Gi

config:
  batchSize: "1048576"
