configuration:
  config: |
    ---
    metrics:
      - name: bootstrapper
        path: '{ .result }'
        help: Bootstrap node moniker
        labels:
          network: '{.network}'
          location: '{.moniker}'
        values:
          network: '{.network}'
          location: '{.moniker}'

      - name: sync_info
        type: object
        help: Sync information from the Celestia bootstrappers
        path: '{ .result }'
        labels:
          latest_block_height: '{ .sync_info.latest_block_height }'
          latest_block_time: '{ .sync.latest_block_time}'
        values:
          latest_block_height: '{ .sync_info.latest_block_height }'
          latest_block_time: '{ .sync_info.latest_block_time}'
    headers:
      X-Dummy: celestia
