service:
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 3000
  annotations: {}
  labels: {}
  portname: service

sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
  dashboards:
    enabled: true

plugins:
  - grafana-piechart-panel

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter:
      gnetId: 1860
      revision: 15
      datasource: Prometheus
    deployments:
      gnetId: 8588
      revision: 1
      datasource: Prometheus
    celestia:
      gnetId: 16610
      revision: 2
      datasource: Prometheus
